Update CODEOWNERS
gruntwork-io/kubergrunt pull request #175
Opened 2022-09-30 16:41 UTC by yorinasub17

Removes myself from CODEOWNERS for the upcoming transition.

2022-10-04 16:00 UTC, autero1 commented on CODEOWNERS
> +* @zackproser @rhoboat  @autero1
```suggestion
* @zackproser @autero1
```

2022-10-04 16:01 UTC, autero1 submitted a review, later dismissed

2023-04-05 23:35 UTC, pras111gw requested changes
remove @autero1 and add @pras111gw

2023-04-05 23:38 UTC, pras111gw approved these changes

2023-04-06 07:17 UTC, marinalimeira approved these changes

2023-04-06 07:22 UTC, merged