Added ECR repo ID for Regions
gruntwork-io/kubergrunt pull request #192
Opened 2023-04-04 06:45 UTC by rajkz

Regions added:

ap-southeast-3
ap-south-2
ap-southeast-4
eu-central-2
eu-south-2
me-central-1

## Description

Fixes #000.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### Migration Guide

2023-04-05 21:14 UTC, arsci commented
Thanks for your submission, @rajkz ! I'll kick off automated tests

2023-04-05 21:41 UTC, arsci requested changes

2023-04-05 21:41 UTC, arsci commented on eks/sync.go
> +		"me-central-1":   "759879836304"
Tests are failing on syntax, I think you might need to add a trailing `,` here.

2023-07-06 01:28 UTC, pras111gw approved these changes
lgtm

2023-07-07 22:41 UTC, pras111gw commented
This commit is merged into issue/201 branch and will be released in next few days.

2023-07-07 22:41 UTC, closed without merging